PR
SASHKEVICH/iOS-FakeNFT-StarterProject-Public pull request #46
Opened 2023-08-21 07:03 UTC by 777EXX

2023-08-21 11:32 UTC, SASHKEVICH commented
@777EXX Не забудь приложить ссылочку на файлик с декомпозицией в описании ПРа

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Foundation/Observable.swift
> +    private var onChange: ((Value) -> Void)? = nil
Смотри сам, конечно, но я и Дмитрий использовали такую вишку как [Box](https://www.kodeco.com/6733535-ios-mvvm-tutorial-refactoring-from-mvc). Вполне удобно, как мне показалось, и опять же с `propertyWrappers` особо заморачиваться не надо. Плюс, поля, реализованные с помощью `Box`, можно очень просто поместить в протокол, чего не скажешь о `propertyWrappers`

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Models/Network/Nft/Nft.swift
> +    let images: [String]
Обрати внимание, что при мерже надо будет вот такие структурки выпиливать, потому что, по сути, мы вчетвером написали одно и то же)

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Scenes /Statistic/ProfileCollection/NftCollectionCell.swift
> +    var delegate: NftCollectionCellDelegate? = nil
Опциональные поля и переменные по умолчанию имеют значение `nil`. Думаю, можно убрать явное обозначение

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Scenes /Statistic/ProfileCollection/ProfileCollectionViewController.swift
> +    private let viewModel = ProfileCollectionViewModel()
Вьюмодель лучше передавать как зависимость через конструктор класса. `Dependency Inversion Principle` и все дела

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Scenes /Statistic/ProfileCollection/ProfileCollectionViewController.swift
> +    private var nftList: [Nft] = []
Мне кажется, о списке nft должна знать именно вьюмодель, а не контроллер

2023-08-21 11:57 UTC, SASHKEVICH commented on FakeNFT/Services/Nft/NftNetworkService.swift
> +    private let client = DefaultNetworkClient()
Тоже `Dependency Inversion Principle`. Нужно, чтобы сервис зависел от клиента.
Но, на самом деле, у нас у всех почти есть реализация вот такого сервиса, поэтому надо просто их переиспользовать. Но это после мержа уже

2023-08-23 16:35 UTC, protos17 requested changes

2023-08-23 16:35 UTC, protos17 commented on FakeNFT/Foundation/GeometricParams.swift
> +    public init(cellCount: Int, leftInset: CGFloat, rightInset: CGFloat, cellHorizontalSpacing: CGFloat, cellVerticalSpacing: CGFloat) {
Рекомендую убрать public, они тут лишние

2023-08-23 16:35 UTC, protos17 commented on Decomposition/statitic_plan.md
Декомпозиция отличается от той, что ты указывал в 19 спринте

2023-08-23 16:35 UTC, protos17 commented on FakeNFT/Foundation/GeometricParams.swift
> +//  Created by macOS on 23.06.2023.
Файлы созданы Баянкиным Максимом еще 23 июня

2023-09-12 12:33 UTC, closed without merging